#!/bin/bash
LIBGL_ALWAYS_INDIRECT=0
LIBGL_ALWAYS_SOFTWARE=1
PROFILEDIR="${HOME}/dev/scilab"

docker run --name scilab --rm --net=host \
       --env="DISPLAY" \
       --env="LIBGL_ALWAYS_INDIRECT" \
       --env="LIBGL_ALWAYS_SOFTWARE" \
       --mount "type=bind,src=${HOME}/.Xauthority,dst=/home/scilab/.Xauthority,readonly" \
       --mount "type=bind,src=${PROFILEDIR},dst=/home/scilab/.Scilab" \
       andzuc/debian-scilab
